### ISSUE TITLE
Remove German Config

### ISSUE THREAD

**Issue by Aevyz** [lupuleasa-core/Dota2-TheCore-Config-Engine#158]
Correct me if I am wrong, but with the `Bind keys based on keyboard position` toggle, the need for a qwertz configuration should no longer be needed. The only thing we might need to add is a note in the ReadMe if `dota_remap_alt_key` is required. 

Plus: We have not updated that thing in a while, I am pretty sure most of it is still broken from spring cleaning

**Comment by dodekeract** [comment]
As a German using a QWERTZ keyboard, I never had any issues with position-based-binding, so I'd :+1: this.

**Comment by loopuleasa** [comment]
I could do something like that when I get home.

Can folks confirm there are no issues at the moment with my layout on non-standard keyboard setups?
